services:
  
  ragnarock-gasolin:
    image: vlysiumdev/ragnarock-gasolin:latest
    container_name: ragnarock-gasolin_web
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - web-proxy
    restart: unless-stopped

# use reverse proxy container on cloud server
networks:
  web-proxy:
    external: true 