services:
  
  ragnarock-gasolin:
    image: vlysiumdev/ragnarock-gasolin:latest
    container_name: ragnarock-gasolin_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - nginx
    restart: unless-stopped

# use reverse proxy container on cloud server
networks:
  nginx:
    external: true 